[package]
name = "web_framework_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.99"
di_ioc_lib = { path = "../di_ioc_lib" }
